### ISSUE TITLE
Can not express "rdf:type"

### ISSUE THREAD

**Issue by linonetwo** [rubensworks/graphql-to-sparql.js#17]
```graphql
{ container: Container(type: "<http://www.w3.org/ns/ldp#Container>") { contains } }
```
Turns into 
```sparql
SELECT ?container_contains WHERE {
  _:b1 <ldp:Container> ?container.
  ?container <rdf:type> "<http://www.w3.org/ns/ldp#Container>";
    <ldp:contains> ?container_contains.
}
```
Which is not returning any result.

While this one works:
```diff
  SELECT ?container_contains WHERE {
-    _:b1 <ldp:Container> ?container.
-    ?container <rdf:type> "<http://www.w3.org/ns/ldp#Container>";
+    ?container rdf:type <http://www.w3.org/ns/ldp#Container>;
-     <ldp:contains> ?container_contains.
+     ldp:contains ?container_contains.
  }
```

1. How can I get `rdf:type` and `ldp:contains` instead of `<rdf:type>` and `<ldp:contains>`?
2. How can I remove the `_:b1 <ldp:Container> ?container.`?

**Comment by rubensworks** [comment]
> 1. How can I get rdf:type and ldp:contains instead of <rdf:type> and <ldp:contains>?

This is the same problem as #18.

> 2. How can I remove the _:b1 <ldp:Container> ?container.?

You can use [inline fragments](https://github.com/rubensworks/graphql-to-sparql.js#inline-fragments) for this:

```graphql
{
  ... on Container {
    contains
  }
}
```

This will output something like this:

```sparql
SELECT ?container_contains WHERE {
  OPTIONAL {
    ?container rdf:type "<http://www.w3.org/ns/ldp#Container>";
      ldp:contains ?container_contains.
  }
}
```

Does this work for you?

**Comment by linonetwo** [comment]
This is exactly what I want, thank you!
