### ISSUE TITLE
Context not expanded properly

### ISSUE THREAD

**Issue by linonetwo** [rubensworks/graphql-to-sparql.js#18]
I'm using https://raw.githubusercontent.com/solid/query-ldflex/master/src/context.json for my GraphQL-LD query.

But `{ ldp:contains }` will result in `SELECT ?ldp WHERE { _:b1 undefined:contains ?ldp. }`

If I add `"contains": "ldp:contains",` to context.json, the result is still not correct:
`{ contains }` result in `SELECT ?contains WHERE { _:b1 <ldp:contains> ?contains. }`
`{ ldp:contains }` result in `SELECT ?ldp WHERE { _:b1 <ldp:contains> ?ldp. }`

**Comment by linonetwo** [comment]
Okay, maybe JSON-LD context is not recursively expandable?

**Comment by linonetwo** [comment]
I currently using a workaround:

```js
mapValues(ldpContext, value => {
    const [prefix, suffix] = value.split(':');
    if (ldpContext[prefix]) {
      return ldpContext[prefix] + suffix;
    }
    return value;
  })
```

**Comment by rubensworks** [comment]
Merging this issue in #24.
