### ISSUE TITLE
Allow sending graphql document node instead of graphql string

### ISSUE THREAD

**Issue by allforabit** [rubensworks/graphql-to-sparql.js#29]
I'm working on an apollo link that integrates this library. From my initial investigation it looks like the already parsed graphql query is only available for this api. I could serialize it back to a string to work with this but maybe it would make sense to allow a string _or_ a graphql document node as the first argument to `graphqlToSparqlAlgebra`?

**Comment by rubensworks** [comment]
Sure, that definitely makes sense!
